# Generated by Django 5.2.5 on 2026-01-03 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Optional bot name", max_length=100
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("qty", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stop_pct",
                    models.DecimalField(
                        decimal_places=2, help_text="Stop loss percentage", max_digits=5
                    ),
                ),
                (
                    "trailing_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Trailing stop percentage",
                        max_digits=5,
                    ),
                ),
                ("long_account", models.CharField(max_length=50)),
                ("short_account", models.CharField(max_length=50)),
                ("port", models.IntegerField(default=7497)),
                (
                    "use_algo",
                    models.BooleanField(
                        default=False, help_text="Use IBKR Adaptive algo"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("RUNNING", "Running"),
                            ("STOPPED", "Stopped"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="IDLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "trading_bots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "status"],
                        name="trading_bot_symbol_3c9cad_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="trading_bot_created_1d86a5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cycle_number",
                    models.IntegerField(
                        help_text="Sequential cycle number for this bot"
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "contract_id",
                    models.IntegerField(blank=True, help_text="IBKR conId", null=True),
                ),
                (
                    "min_tick",
                    models.DecimalField(decimal_places=6, default=0.01, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIALIZING", "Initializing"),
                            ("ENTERING", "Entering Positions"),
                            ("ACTIVE", "Active with Protection"),
                            ("TRANSITIONING", "Transitioning to Trailing"),
                            ("EXITING", "Exiting Positions"),
                            ("COMPLETED", "Completed"),
                            ("ABORTED", "Aborted"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="INITIALIZING",
                        max_length=20,
                    ),
                ),
                (
                    "total_buys",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_sells",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Computed: sells - buys - commission",
                        max_digits=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="trading.bot",
                    ),
                ),
            ],
            options={
                "db_table": "trading_cycles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.IntegerField(db_index=True, help_text="IBKR orderId"),
                ),
                (
                    "order_ref",
                    models.CharField(
                        blank=True, help_text="Custom order reference", max_length=100
                    ),
                ),
                (
                    "perm_id",
                    models.IntegerField(blank=True, help_text="IBKR permId", null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LONG_ENTRY", "Long Entry"),
                            ("SHORT_ENTRY", "Short Entry"),
                            ("LONG_SL", "Long Stop Loss"),
                            ("SHORT_SL", "Short Stop Loss"),
                            ("LONG_TRAIL", "Long Trailing Stop"),
                            ("SHORT_TRAIL", "Short Trailing Stop"),
                            ("PANIC_FLATTEN", "Panic Flatten"),
                            ("PROT_FAIL_FLATTEN", "Protection Failure Flatten"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("account", models.CharField(max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        help_text="Market, Stop, Trail, etc.", max_length=20
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "trailing_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PendingSubmit", "Pending Submit"),
                            ("PreSubmitted", "Pre-Submitted"),
                            ("Submitted", "Submitted"),
                            ("Filled", "Filled"),
                            ("PartiallyFilled", "Partially Filled"),
                            ("Cancelled", "Cancelled"),
                            ("ApiCancelled", "API Cancelled"),
                            ("Inactive", "Inactive"),
                            ("Rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="PendingSubmit",
                        max_length=20,
                    ),
                ),
                (
                    "filled_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "avg_fill_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_update_at", models.DateTimeField(auto_now=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trading.cycle",
                    ),
                ),
            ],
            options={
                "db_table": "trading_orders",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exec_id",
                    models.CharField(
                        db_index=True,
                        help_text="IBKR execution ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("shares", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=4, max_digits=15)),
                ("account", models.CharField(max_length=50)),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("commission_currency", models.CharField(default="USD", max_length=3)),
                (
                    "realized_pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="IBKR reported realized P&L",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("executed_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="trading.cycle",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="trading.order",
                    ),
                ),
            ],
            options={
                "db_table": "trading_executions",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("BOT_START", "Bot Started"),
                            ("BOT_STOP", "Bot Stopped"),
                            ("CYCLE_START", "Cycle Started"),
                            ("CYCLE_COMPLETE", "Cycle Completed"),
                            ("CYCLE_ABORT", "Cycle Aborted"),
                            ("ORDER_SUBMITTED", "Order Submitted"),
                            ("ORDER_FILLED", "Order Filled"),
                            ("ORDER_CANCELLED", "Order Cancelled"),
                            ("ORDER_REJECTED", "Order Rejected"),
                            ("STOP_LOSS_HIT", "Stop Loss Triggered"),
                            ("TRANSITION_START", "Transition Started"),
                            ("TRANSITION_COMPLETE", "Transition Completed"),
                            ("TRAILING_UPDATE", "Trailing Stop Updated"),
                            ("POSITION_FLAT", "Position Flattened"),
                            ("PANIC_FLATTEN", "Panic Flatten"),
                            ("IBKR_ERROR", "IBKR Error"),
                            ("SYSTEM_ERROR", "System Error"),
                            ("PNL_REPORT", "P&L Report"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional structured event data",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "bot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="trading.bot",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="trading.cycle",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="trading.order",
                    ),
                ),
            ],
            options={
                "db_table": "trading_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cycle",
            index=models.Index(
                fields=["bot", "cycle_number"], name="trading_cyc_bot_id_49c52a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cycle",
            index=models.Index(fields=["status"], name="trading_cyc_status_aa9410_idx"),
        ),
        migrations.AddIndex(
            model_name="cycle",
            index=models.Index(
                fields=["created_at"], name="trading_cyc_created_d32744_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cycle",
            unique_together={("bot", "cycle_number")},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["cycle", "role"], name="trading_ord_cycle_i_7553e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_id"], name="trading_ord_order_i_c7175c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="trading_ord_status_65490f_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["submitted_at"], name="trading_ord_submitt_68fd09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(
                fields=["cycle", "executed_at"], name="trading_exe_cycle_i_e33353_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(
                fields=["order", "executed_at"], name="trading_exe_order_i_c10fbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["bot", "created_at"], name="trading_eve_bot_id_10b530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["cycle", "created_at"], name="trading_eve_cycle_i_b00234_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="trading_eve_event_t_eca820_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["level", "created_at"], name="trading_eve_level_1c1c4d_idx"
            ),
        ),
    ]
