# Generated by Django 5.2.5 on 2026-01-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="currency",
            field=models.CharField(
                default="USD",
                help_text="Currency (e.g., 'USD', 'EUR', 'GBP')",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="exchange",
            field=models.CharField(
                default="SMART",
                help_text="Routing exchange (usually 'SMART' for automatic routing)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="primary_exchange",
            field=models.CharField(
                blank=True,
                help_text="Primary exchange (e.g., 'NYSE', 'NASDAQ', 'SBF'). Leave blank if not needed.",
                max_length=20,
            ),
        ),
    ]
