# Generated by Django 5.2.9 on 2026-01-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_bot_currency_bot_exchange_bot_primary_exchange"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="port",
        ),
        migrations.AddField(
            model_name="bot",
            name="environment",
            field=models.CharField(
                choices=[("PAPER", "Paper Trading"), ("LIVE", "Live Trading")],
                default="PAPER",
                help_text="Trading environment (Paper: port 7497, Live: port 7496)",
                max_length=10,
            ),
        ),
    ]
