# Generated by Django 5.1.4 on 2026-01-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_bot_port_bot_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='worker_task_id',
            field=models.CharField(max_length=255, null=True, blank=True,
                                  help_text="Procrastinate task ID of the running worker (for multi-worker deduplication)"),
        ),
        migrations.AddField(
            model_name='bot',
            name='worker_started_at',
            field=models.DateTimeField(null=True, blank=True,
                                      help_text="When the current worker task started"),
        ),
    ]
