# Generated by Django 5.2.5 on 2026-01-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0004_add_worker_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="worker_last_heartbeat",
            field=models.DateTimeField(
                blank=True,
                help_text="Last heartbeat from the worker (updated every 30s)",
                null=True,
            ),
        ),
    ]
