# Generated by Django 5.2.9 on 2026-01-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0005_add_worker_heartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="last_client_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Persisted clientId to reuse across restarts",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("BOT_START", "Bot Started"),
                    ("BOT_STOP", "Bot Stopped"),
                    ("CYCLE_START", "Cycle Started"),
                    ("CYCLE_COMPLETE", "Cycle Completed"),
                    ("CYCLE_ABORT", "Cycle Aborted"),
                    ("ORDER_SUBMITTED", "Order Submitted"),
                    ("ORDER_FILLED", "Order Filled"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("ORDER_REJECTED", "Order Rejected"),
                    ("STOP_LOSS_HIT", "Stop Loss Triggered"),
                    ("TRANSITION_START", "Transition Started"),
                    ("TRANSITION_COMPLETE", "Transition Completed"),
                    ("TRAILING_UPDATE", "Trailing Stop Updated"),
                    ("POSITION_FLAT", "Position Flattened"),
                    ("PANIC_FLATTEN", "Panic Flatten"),
                    ("IBKR_ERROR", "IBKR Error"),
                    ("SYSTEM_ERROR", "System Error"),
                    ("PNL_REPORT", "P&L Report"),
                    ("BACKFILL_APPLIED", "Executions Backfilled"),
                    ("BACKFILL_SKIP_NO_ID", "Backfill Skipped Missing ID"),
                    ("BACKFILL_MISSING_ORDER", "Backfill Missing Order"),
                    ("CYCLE_RECONCILED", "Cycle Reconciled"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
