# Generated by Django 5.2.5 on 2026-01-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0006_persist_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("BOT_START", "Bot Started"),
                    ("BOT_STOP", "Bot Stopped"),
                    ("CYCLE_START", "Cycle Started"),
                    ("CYCLE_COMPLETE", "Cycle Completed"),
                    ("CYCLE_ABORT", "Cycle Aborted"),
                    ("CYCLE_ABORTED", "Cycle Aborted"),
                    ("CYCLE_AUTO_COMPLETED", "Cycle Auto-Completed"),
                    ("CYCLE_ENTRY_START", "Cycle Entry Started"),
                    ("CYCLE_ERROR", "Cycle Error"),
                    ("CYCLE_FAILED", "Cycle Failed"),
                    ("CYCLE_RECONCILED", "Cycle Reconciled"),
                    ("CYCLE_RECOVERED", "Cycle Recovered"),
                    ("ORDER_SUBMITTED", "Order Submitted"),
                    ("ORDER_FILLED", "Order Filled"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("ORDER_REJECTED", "Order Rejected"),
                    ("ENTRY_CANCELLED", "Entry Cancelled"),
                    ("ENTRY_FAILURE", "Entry Failure"),
                    ("ENTRY_PENDING", "Entry Pending"),
                    ("STOP_LOSS_HIT", "Stop Loss Triggered"),
                    ("TRANSITION_START", "Transition Started"),
                    ("TRANSITION_COMPLETE", "Transition Completed"),
                    ("TRAILING_UPDATE", "Trailing Stop Updated"),
                    ("POSITION_FLAT", "Position Flattened"),
                    ("POSITIONS_FLAT", "Positions Flattened"),
                    ("HEDGE_ACTIVE", "Hedge Active"),
                    ("PROTECTION_START", "Protection Started"),
                    ("PROTECTION_FAILURE", "Protection Failure"),
                    ("QTY_MISMATCH", "Quantity Mismatch"),
                    ("PANIC_FLATTEN", "Panic Flatten"),
                    ("PREFLIGHT_BLOCKED", "Preflight Check Blocked"),
                    ("VALIDATION_PASSED", "Validation Passed"),
                    ("VALIDATION_FAILED", "Validation Failed"),
                    ("RECOVERY_BLOCKED", "Recovery Blocked"),
                    ("IBKR_ERROR", "IBKR Error"),
                    ("SYSTEM_ERROR", "System Error"),
                    ("PNL_REPORT", "P&L Report"),
                    ("BACKFILL_APPLIED", "Executions Backfilled"),
                    ("BACKFILL_SKIP_NO_ID", "Backfill Skipped Missing ID"),
                    ("BACKFILL_MISSING_ORDER", "Backfill Missing Order"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
